---
serviceAccount:
  name: argocd-image-updater

authScripts:
  enabled: true
  scripts:
    auth.sh: |
      #!/bin/sh
      aws ecr --region eu-central-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

config:
  registries:
  - name: ECR
    api_url: https://438950223046.dkr.ecr.eu-central-1.amazonaws.com
    prefix: 438950223046.dkr.ecr.eu-central-1.amazonaws.com
    ping: yes
    insecure: no
    credentials: ext:/scripts/auth.sh
    credsexpire: 10h