apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging # Nazwa, której będziesz używać w Ingressach
  annotations:
    # TO JEST KLUCZ! Ten zasób wdroży się w fali -2. 
    # Dzięki temu cert-manager (fala -3) zdąży wstać, zainstalować CRD i Webhooki,
    # zanim ArgoCD spróbuje to zaaplikować!
    # argocd.argoproj.io/sync-wave: "-2"
spec:
  acme:
    # Serwer weryfikacyjny Let's Encrypt STAGING
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: bzyk0945@gmail.com # Tu będą przychodzić powiadomienia o wygaśnięciu
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    # Używamy metody weryfikacji DNS-01 (wymagana dla certyfikatów Wildcard i subdomen)
    - dns01:
        route53:
          region: eu-central-1
          # Zwróć uwagę, że NIE podajemy tu AccessKey ani SecretKey!
          # Wszystko dzieje się magicznie dzięki EKS Pod Identity podpiętemu 
          # do ServiceAccount w pliku values-base.yaml.