deploymentMode: SimpleScalable

loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2026-03-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: s3

serviceAccount:
  create: true
  name: loki