apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-cert-manager-issuers
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
  template:
    metadata:
      name: '{{env}}-cert-manager-issuer'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/k-napiontek/test.git'
        targetRevision: HEAD
        path: '03-gitops-infra/manifests/cert-manager/{{env}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
