apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-cluster-microservices
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/k-napiontek/test.git # TODO: Change to the actual repo URL
      revision: main
      directories:
        - path: 04-gitops-apps/manifests/*
  template:
    metadata:
      name: 'staging-{{path.basename}}'
      labels:
        environment: staging
    spec:
      project: default
      source:
        repoURL: https://github.com/k-napiontek/test.git # TODO: Change to the actual repo URL
        targetRevision: main
        path: '{{path}}/overlays/staging'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-staging'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2   
            maxDuration: 3m 