apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: my-image-updater
  namespace: argocd
spec:
  namespace: argocd  
  applicationRefs:
    - namePattern: "backend-dev"  
      images:
        - alias: "backend-dev"
          imageName: "438950223046.dkr.ecr.eu-central-1.amazonaws.com/dev-myapp-backend:v1.0.2"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-backend=438950223046.dkr.ecr.eu-central-1.amazonaws.com/dev-myapp-backend
    argocd-image-updater.argoproj.io/my-backend.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: 'https://github.com/k-napiontek/test.git'  
    targetRevision: HEAD
    path: 04-gitops-apps/manifests/backend/overlays/dev 

  # 3. Cel (gdzie wdrożyć)
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: backend-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 