apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=438950223046.dkr.ecr.eu-central-1.amazonaws.com/dev-myapp-backend
    argocd-image-updater.argoproj.io/my-backend.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  
spec:
  source:
    path: 04-gitops-apps/manifests/backend/overlays/dev