apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: my-image-updater
  namespace: argocd
spec:
  namespace: argocd  
  applicationRefs:
    - namePattern: "backend-dev"  
      images:
        - alias: "backend-dev"
          imageName: "438950223046.dkr.ecr.eu-central-1.amazonaws.com/dev-myapp-backend"
          
      commonUpdateSettings:
        updateStrategy: "semver"
        
      # CORRECTED SCHEMA: writeBackConfig belongs at the applicationRef level
      writeBackConfig:
        # The method defines both that we are using Git AND which secret holds the token
        method: "git:secret:argocd/github-creds"
        gitConfig:
          branch: "main"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/k-napiontek/test.git'  
    targetRevision: HEAD
    path: 04-gitops-apps/manifests/backend/overlays/dev 

  # 3. Cel (gdzie wdrożyć)
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: backend-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 