apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=438950223046.dkr.ecr.eu-central-1.amazonaws.com/dev-myapp
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest 
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  source:
    path: 04-gitops-apps/manifests/frontend/overlays/dev