apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-stg
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/k-napiontek/test.git'
    targetRevision: HEAD
    path: 04-gitops-apps/manifests/frontend/overlays/stg

  destination:
    # TODO: Update to stg cluster URL after provisioning
    server: 'https://kubernetes.default.svc'
    namespace: frontend-stg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
