apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cert-manager-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/k-napiontek/test.git'
    targetRevision: HEAD
    path: '03-gitops-infra/manifests/cert-manager/dev'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true