apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-infra
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: dev

          - git:
              repoURL: 'https://github.com/k-napiontek/test.git'
              revision: HEAD
              files:
                - path: '03-gitops-infra/components/*/config.yaml'

  template:
    metadata:
      name: '{{env}}-infra-{{app}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: default
      sources:
        - repoURL: '{{repoURL}}'
          chart: '{{chart}}'
          targetRevision: '{{version}}'
          helm:
            valueFiles:
              - $values/03-gitops-infra/components/{{app}}/base.yaml
              - $values/03-gitops-infra/components/{{app}}/{{env}}.yaml

        - repoURL: 'https://github.com/k-napiontek/test.git'
          targetRevision: HEAD
          ref: values

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true