dev/00-network:
- '01-terraform-infra/envs/dev/00-network/**'
- '01-terraform-infra/modules/**'
dev/20-compute:
- '01-terraform-infra/envs/dev/20-compute/**'
- '01-terraform-infra/modules/**'
dev/30-bootstrap:
- '01-terraform-infra/envs/dev/30-bootstrap/**'
- '01-terraform-infra/modules/**'


stg/00-network:
- '01-terraform-infra/envs/stg/00-network/**'
- '01-terraform-infra/modules/**'
stg/20-compute:
- '01-terraform-infra/envs/stg/20-compute/**'
- '01-terraform-infra/modules/**'
stg/30-bootstrap:
- '01-terraform-infra/envs/stg/30-bootstrap/**'
- '01-terraform-infra/modules/**'


prod/00-network:
- '01-terraform-infra/envs/prod/00-network/**'
- '01-terraform-infra/modules/**'
prod/20-compute:
- '01-terraform-infra/envs/prod/20-compute/**'
- '01-terraform-infra/modules/**'
prod/30-bootstrap:
- '01-terraform-infra/envs/prod/30-bootstrap/**'
- '01-terraform-infra/modules/**'