global/ecr:
  - '01-terraform-infra/global/ecr/**'
  - '01-terraform-infra/modules/ecr/**'

dev/00-network:
  - '01-terraform-infra/envs/dev/00-network/**'
  - '01-terraform-infra/modules/vpc/**'
dev/20-compute:
  - '01-terraform-infra/envs/dev/20-compute/**'
  - '01-terraform-infra/envs/dev/00-network/**'
  - '01-terraform-infra/modules/eks/**'
  - '01-terraform-infra/modules/alb/**'
dev/30-bootstrap:
  - '01-terraform-infra/envs/dev/30-bootstrap/**'
  - '01-terraform-infra/envs/dev/20-compute/**'
  - '01-terraform-infra/envs/dev/00-network/**'
  - '01-terraform-infra/modules/argocd/**'

stg/00-network:
  - '01-terraform-infra/envs/stg/00-network/**'
  - '01-terraform-infra/modules/vpc/**'
stg/20-compute:
  - '01-terraform-infra/envs/stg/20-compute/**'
  - '01-terraform-infra/envs/stg/00-network/**'
  - '01-terraform-infra/modules/eks/**'
  - '01-terraform-infra/modules/alb/**'
stg/30-bootstrap:
  - '01-terraform-infra/envs/stg/30-bootstrap/**'
  - '01-terraform-infra/envs/stg/20-compute/**'
  - '01-terraform-infra/envs/stg/00-network/**'
  - '01-terraform-infra/modules/argocd/**'

prod/00-network:
  - '01-terraform-infra/envs/prod/00-network/**'
  - '01-terraform-infra/modules/vpc/**'
prod/20-compute:
  - '01-terraform-infra/envs/prod/20-compute/**'
  - '01-terraform-infra/envs/prod/00-network/**'
  - '01-terraform-infra/modules/eks/**'
  - '01-terraform-infra/modules/alb/**'
prod/30-bootstrap:
  - '01-terraform-infra/envs/prod/30-bootstrap/**'
  - '01-terraform-infra/envs/prod/20-compute/**'
  - '01-terraform-infra/envs/prod/00-network/**'
  - '01-terraform-infra/modules/argocd/**'
