apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd 
spec:
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.0.0
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        webhook:
          create: true
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::438950223046:role/external-secrets-role
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets 
  project: default 
  syncPolicy:     
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - ServerSideApply=true