apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-dev
  namespace: argocd
spec:
  project: default  
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.20.0
      helm:
        valueFiles:
          - $values/03-gitops-infra/manifests/external-dns/values.yaml
    - repoURL: 'https://github.com/k-napiontek/test.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true