---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-token-refresher
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-secret-manager-role
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-manager-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: ecr-token-refresher
    namespace: argocd
roleRef:
  kind: Role
  name: ecr-secret-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-token-refresher
  namespace: argocd
spec:
  # Run every 6 hours (ECR tokens expire after 12 hours)
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-token-refresher
          restartPolicy: Never
          containers:
            - name: refresher
              image: public.ecr.aws/aws-cli/aws-cli:latest
              env:
                - name: AWS_REGION
                  value: "eu-central-1" # Your ECR Region
                - name: ECR_REGISTRY
                  value: "438950223046.dkr.ecr.eu-central-1.amazonaws.com" # Your Registry URL
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "1. Fetching ECR token via EKS Pod Identity..."
                  TOKEN=$(aws ecr get-login-password --region $AWS_REGION)
                  
                  echo "2. Downloading kubectl (pinned version for stability)..."
                  curl -sLO "https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl"
                  chmod +x kubectl
                  
                  echo "3. Creating or updating the Kubernetes Secret..."
                  # The --dry-run=client | apply -f - pattern ensures this works for both 
                  # initial creation and subsequent updates without failing.
                  ./kubectl create secret docker-registry ecr-pull-secret \
                    --docker-server=$ECR_REGISTRY \
                    --docker-username=AWS \
                    --docker-password=$TOKEN \
                    --namespace=argocd \
                    --dry-run=client -o yaml | ./kubectl apply -f -
                  
                  echo "4. Success! ECR token refreshed."
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      chart: argocd-image-updater
      targetRevision: 1.1.0
      helm:
        valueFiles:
          - $values/03-gitops-infra/manifests/image-updater/values-prod.yaml
    - repoURL: 'https://github.com/k-napiontek/test.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true